/*
 * This source file was generated by the Gradle 'init' task
 */
package app;

import java.io.File;
import com.fasterxml.jackson.databind.ObjectMapper;


class Config {
    public String botToken;
}

public class App {
    static Config config;

    public static void main(String[] args) {
        ObjectMapper mapper = new ObjectMapper();
        try {
            config = mapper.readValue(new File("src/config.json"), Config.class);

            SlashBot slashBot = new SlashBot(config.botToken);
        } catch(Exception e){
            e.printStackTrace();
        }
    }
}